# Generated by Django 2.1.1 on 2019-08-26 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0002_doc_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doc',
            name='author',
        ),
        migrations.RemoveField(
            model_name='doc',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='doc',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='doc',
            name='file_url',
        ),
        migrations.RemoveField(
            model_name='doc',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='doc',
            name='title',
        ),
    ]
