# Generated by Django 2.1.1 on 2019-08-27 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_comments_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='parent',
        ),
    ]
