# Generated by Django 2.1.1 on 2019-09-15 07:24

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20190910_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image_url',
            field=models.CharField(default='', help_text='图片url', max_length=200, validators=[utils.validators.MediaUrlValidator()], verbose_name='图片url'),
        ),
    ]
