# Generated by Django 2.1.1 on 2019-09-02 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('name', models.CharField(help_text='菜单名', max_length=48, unique=True, verbose_name='菜单名')),
                ('url', models.CharField(blank=True, help_text='url', max_length=256, null=True, verbose_name='路由名称')),
                ('order', models.SmallIntegerField(default=0, verbose_name='排序')),
                ('icon', models.CharField(default='fa-link', max_length=48, verbose_name='图标')),
                ('codename', models.CharField(help_text='权限码', max_length=48, unique=True, verbose_name='权限码')),
                ('is_visible', models.BooleanField(default=False, verbose_name='是否可见')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='myadmin.Menu', verbose_name='父菜单')),
                ('permission', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Permission')),
            ],
            options={
                'verbose_name': '菜单',
                'verbose_name_plural': '菜单',
                'db_table': 'tb_menu',
                'ordering': ['-order'],
            },
        ),
    ]
